repartition: True
arch_root: /mnt
country: United States
locales:
  - en_US
  - uk_UA

user:
  name: zoresvit
  comment: Ruslan Kiianchuk
  group: zoresvit
  groups:
    - sys
    - video
    - wheel
  shell: /bin/bash
  email: ruslan.kiianchuk@gmail.com
