hostname: vbox
uefi: false

drivers:
  - nvidia-340xx-libgl
  - virtualbox-guest-modules-arch
  - virtualbox-guest-utils

# UEFI/GPT
#disks:
#  - device: /dev/sda
#    table: gpt
#    partitions:
#
#      - name: efi
#        start: 1MiB
#        end: 512MiB
#        type: EPS
#        fstype: vfat
#        mountpoint: /boot/efi
#
#      - name: lvm
#        start: 512MiB
#        end: 100%
#        type: primary
#        lvm_group: arch


# BIOS/GPT
disks:
  - device: /dev/sda
    table: gpt
    partitions:

      - name: bios_grub
        start: 0MiB
        end: 2MiB
        type: bios_grub

      - name: efi
        start: 2MiB
        end: 512MiB
        type: EPS
        fstype: vfat
        mountpoint: /boot/efi

      - name: lvm
        start: 512MiB
        end: 100%
        type: primary
        lvm_group: arch

lvm:
  - group: arch
    volumes:
      - name: root
        size: 10G
        fstype: ext4
        mountpoint: /

      - name: var
        size: 2G
        fstype: ext4
        mountpoint: /var

      - name: home
        size: 100%FREE
        fstype: ext4
        mountpoint: /home
