hostname: xps

drivers:
  - xf86-video-intel

disks:
  - device: /dev/sda
    table: gpt
    partitions:

      - name: efi
        start: 1MiB
        end: 512MiB
        type: EPS
        fstype: vfat
        mountpoint: /boot/efi

      - name: lvm
        start: 512MiB
        end: 100%
        type: primary
        lvm_group: arch

lvm:
  - group: arch
    volumes:
      - name: root
        size: 20G
        fstype: ext4
        mountpoint: /

      - name: var
        size: 5G
        fstype: reiserfs
        mountpoint: /var

      - name: home
        size: 100%FREE
        fstype: ext4
        mountpoint: /home
