---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes
  pre_tasks:
    - name: update repository mirrors
      command: reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist

  roles:
    - pacman
    - aur

  tasks:
    - name: install Bash completion
      pacman: name={{ item }} state=present
      with_items:
        - bash-completion

    - name: install Zsh
      pacman: name={{ item }} state=present
      with_items:
        - zsh
        - zsh-completions

    - name: set default shell for user
      command: chsh -s {{ user.shell }} {{ user.name }}
