---
- hosts: localhost
  name: configure Arch Linux system
  connection: local
  become: yes
  pre_tasks:
    - name: update repository mirrors
      command: reflector --sort score -p https --country '{{ country }}' --save /etc/pacman.d/mirrorlist

  roles:
    - pacman
    - aur
    - base
    - grsec
