---
- hosts: localhost
  name: bootstrap base Arch Linux system
  connection: local

  pre_tasks:

    - include_vars: group_vars/vbox.yml
      when: ansible_product_name == "VirtualBox"

    - include_vars: group_vars/gazp9.yml
      when: ansible_product_name == "Gazelle Professional"

    - include_vars: group_vars/xps13.yml
      when: ansible_product_name == "XPS 13 9350"

  roles:
    - arch-bootstrap
