
- name: install packages for desktop environment
  pacman: name={{ item }} state=present
  with_items:
    - lxqt-notificationd
    - gnome-screensaver
    - rxvt-unicode
    - stow
    - keepassx2
    - xmobar
    - stalonetray
    - conky
    - python-pip
    - gvim
    - nigrogen
    - xxkb
    - compton
    - vlc
    - cheese
    - blueman
    - bluez
    - bluez-utils
    - bt-dw1560-firmware

- name: generate SSH key
  command: sudo -u {{ user.name }} ssh-keygen -b 4096 -C {{ user.email }} -P {{ passphrase }} -f ~/.ssh/id_rsa_xps -q

