---
- name: install Xorg server and related apps
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - xf86-input-libinput
    - xorg-apps
    - xorg-server
    - xorg-server-utils
    - xorg-utils
    - xorg-xinit
    - xterm

- name: configure scrolling
  copy: src=30-scrolling.conf dest=/etc/X11/xorg.conf.d/

- name: configure touchpad
  copy: src=30-touchpad.conf dest=/etc/X11/xorg.conf.d/

- name: configure keyboard
  copy: src=30-keyboard.conf dest=/etc/X11/xorg.conf.d/

- name: add user to video group
  user: name={{ user.name }} groups=video append=yes

- name: install apps for GUI improvement
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - unclutter

- name: install AUR apps for GUI improvement
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - acpilight
    - breeze-default-cursor-theme
    - breeze-hacked-cursor-theme
