---
- name: install udisks2 for automount
  pacman: name={{ item }} state=present
  with_items:
    - udisks2
    - udiskie

- name: ensure /media exists
  file: path=/media state=directory

- name: set rule to mount to /media
  copy: src=99-udisks2.rules dest=/etc/udev/rules.d/99-udisks2.rules
