---
- name: install SSH related packages
  pacman: name={{ item }} state=present
  with_items:
    - openssh
    - keychain

- name: push OpenSSH daemon configuration file
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config
  notify:
    - restart sshd

- name: enable and start OpenSSH server daemon
  service: name=sshd.socket enabled=yes state=started
