---

- name: detect boot firmware (UEFI or BIOS)
  shell: '[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS'
  register: firmware

- name: install bootloader packages
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - grub
    - efibootmgr

- name: detect UUID of encrypted device
  command: blkid -s PARTUUID -o value /dev/disk/by-partlabel/{{ encrypt_partition }}
  register: cryptdevice_uuid
  when: encrypt_partition is defined

- name: configure encrypted device for GRUB
  lineinfile: dest=/etc/default/grub regexp=^GRUB_CMDLINE_LINUX= line=GRUB_CMDLINE_LINUX="cryptdevice=PARTUUID={{ cryptdevice_uuid.stdout }}:arch"
  when: encrypt_partition is defined

- name: configure initramfs build hooks
  lineinfile: dest=/etc/mkinitcpio.conf regexp=^HOOKS= line={{ initramfs_hooks }}

- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: install Grub bootloader for UEFI
  command: grub-install --recheck
  when: firmware.stdout == 'UEFI'

- name: install Grub bootloader for BIOS
  command: grub-install --recheck {{ disk.device }}
  when: firmware.stdout == 'BIOS'

- name: create Grub config
  command: grub-mkconfig -o /boot/grub/grub.cfg
