---

- name: detect boot firmware (UEFI or BIOS)
  shell: '[ -d /sys/firmware/efi ] && echo UEFI || echo BIOS'
  register: firmware

- name: install bootloader packages
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - grub
    - efibootmgr

- name: add LVM to initramfs build hook
  lineinfile: dest=/etc/mkinitcpio.conf regexp=^HOOKS= line=HOOKS="base udev autodetect modconf block lvm2 filesystems keyboard fsck"

- name: rebuild initramfs
  command: mkinitcpio -p linux

- name: install Grub bootloader for UEFI
  command: grub-install --recheck
  when: firmware.stdout == 'UEFI'

- name: install Grub bootloader for BIOS
  command: grub-install --recheck {{ item.device }}
  with_items: '{{ disks }}'
  when: firmware.stdout == 'BIOS'

- name: create Grub config
  command: grub-mkconfig -o /boot/grub/grub.cfg
