---
- name: install LXDM display manager
  aur: name=lxdm-git user={{ user.name }}

- name: enable LXDM service
  service: name=lxdm enabled=yes

- name: push LXDM config file
  copy: src=lxdm.conf dest=/etc/lxdm/lxdm.conf backup=yes

- name: install LXDM PostLogin hook
  copy: src=PostLogin dest=/etc/lxdm/PostLogin
