---
- name: install LXDM display manager
  pacman: name=lxdm state=present update_cache=yes

- name: enable LXDM service
  service: name=lxdm enabled=yes

- name: enable LXDM service
  copy: src=lxdm.conf dest=/etc/lxdm/lxdm.conf backup=yes
