hostname: localhost
timezone: America/Los_Angeles
country: United States
locales:
  - en_US

initramfs_hooks: 
  - base 
  - udev 
  - autodetect
  - modconf
  - keyboard
  - block
  - encrypt
  - lvm2
  - filesystems
  - keyboard
  - fsck

packages:
  - arch-wiki-lite
  - coreutils
  - dialog
  - git
  - glances
  - lsof
  - moreutils
  - rsync
  - wpa_supplicant
