---
- include: shell.yml
- include: cron.yml

- name: Enable systemd-timesyncd
  command: timedatectl set-ntp true

- name: install intel microcode
  pacman: name=intel-ucode state=present
  notify:
    - rebuild grub
  when: "'GenuineIntel' in ansible_processor"

- name: install infinality font enhancements
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - freetype2-infinality
    - fontconfig-infinality

- name: install network tools
  pacman: name={{ item }} state=present
  with_items:
    - openvpn
    - mtr
    - whois
    - nmap
    - tcpdump

- name: install text editors
  pacman: name={{ item }} state=present
  with_items:
    - vim

- name: install filesystem packages
  pacman: name={{ item }} state=present
  with_items:
    - dosfstools
    - hfsprogs
    - ntfs-3g
    - exfat-utils


- name: install archive utilities
  pacman: name={{ item }} state=present
  with_items:
    - zip
    - unzip
    - p7zip
    - unrar
    - atool
