---
- include: shell.yml
- include: cron.yml

- name: install intel microcode
  pacman: name=intel-ucode state=present
  notify:
    - rebuild grub
  when: "'GenuineIntel' in ansible_processor"

- name: install infinality font enhancements
  aur: name={{ item }} user={{ user.name }}
  with_items:
    - freetype2-infinality
    - fontconfig-infinality
