---
- include: shell.yml
- include: cron.yml

- name: install custom drivers
  pacman: name={{ item }} state=present update_cache=yes upgrade=yes
  with_items: "{{ drivers }}"
  when: drivers is defined

- name: Enable systemd-timesyncd
  command: timedatectl set-ntp true

- name: install intel microcode
  pacman: name=intel-ucode state=present
  notify:
    - rebuild grub
  when: "'GenuineIntel' in ansible_processor"
  
- name: install filesystem packages
  pacman: name={{ item }} state=present
  with_items:
    - dosfstools
    - hfsprogs
    - ntfs-3g
    - exfat-utils

- name: install archive utilities
  pacman: name={{ item }} state=present
  with_items:
    - zip
    - unzip
    - p7zip
    - unrar
    - atool
