---
- name: install sound utils
  pacman: name={{ item }} state=present
  with_items:
    - alsa-utils 
    - pulseaudio
    - pavucontrol

- name: copy udev rule for USB audio device switching
  copy: src=udev.rules dest=/etc/udev/rules.d/00-local.rules
