- name: install xmonad
  pacman: name={{ item }} state=present update_cache=yes
  with_items:
    - haskell-xmonad
    - haskell-monad-contrib

- name: install xmonad-extras
  aur: name=xmonad-extras-darcs user={{ user.name }}
